services:
  client-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_USERNAME=postgres
      - DB_PASSWORD=Q9379992
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/mydatabase
    depends_on:
      - service-db
      - mongodb
    networks:
      - backend

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Q9379992
      POSTGRES_DB: mydatabase
    ports:
      - "15432:5432"
    restart: unless-stopped
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Q9379992
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  mongo-data:
  pgadmin-data:

networks:
  backend:
